project_id = "eptbjrnqydvkkplousle"

[functions.telegram-webhook]
verify_jwt = false

[functions.top-active-shoutout]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.remix-image]
verify_jwt = false

[functions.mention-users]
verify_jwt = false

[functions.post-random-facts]
verify_jwt = false

[functions.post-daily-gm]
verify_jwt = false

[functions.hourly-memetropolis-post]
verify_jwt = false

[functions.engage-users]
verify_jwt = false