project_id = "eptbjrnqydvkkplousle"

[functions.telegram-webhook]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.remix-image]
verify_jwt = false

[functions.mention-users]
verify_jwt = false