[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['cd telethon-sync && python3 -m pip install -r requirements.txt']

[start]
cmd = 'cd telethon-sync && python3 run_periodic.py'
